### ISSUE TITLE
Describe our dev environment

### ISSUE THREAD

**Issue by jakeharris** [smockle-archive/foodfight#10]
Describe all software and tools we intend to use for our project, including for art assets. Unity3d, Adobe Illustrator, etc.

Areas Addressed:
- Infrastructure (QA)
- Development Environment (Unity?)
- Art Assets
- Audio
- Promotional Website

**Comment by pierceboggan** [comment]
While I am still evaluating several quality assurance/infrastructure-related tools, there are a few that I've narrowed things down to.

#### Continuous Integration
- [TeamCity from JetBrains](http://www.jetbrains.com/teamcity/)
  - Run a TeamCity server with a max of 20 build configurations for free
  - Connect 3 build agents per each server for no cost
  - Upgrade to any new TeamCity version for free
  - Plugins available for Unity3D
- [TravisCI](https://travis-ci.org/)
  - Completely free, only restriction is that our project is open source
  - Potential issue: would have to write our own build scripts / configs

#### Unit Tests
- [SharpUnit](http://wiki.unity3d.com/index.php?title=SharpUnit)
  - Specifically designed for Unity3D
- [NUnitLite](https://github.com/zoon/NUnitLiteUnityRunner)
  - A more popular, commercial testing library that has a Unity-capable test runner
