### ISSUE TITLE
MAR 22th - Organize sketches, report and demo

### ISSUE THREAD

**Issue by smockle** [smockle-archive/foodfight#28]
SKETCHES (Jake, Pierce)
Collect mockups, storyboards and detailed sketches. Provide pencil-and-paper or electronic images of the game. Your design sketches should be sufficiently detailed to allow useful feedback about the design.

REPORT (Jake, Pierce)
Describe how many layers you have finished. You should be most of the way through layer 0 or perhaps even 1 (depending on how aggressive your proposal was). Explain what has proved to be harder (or easier) than expected. What design revisions have you made to your game as a result of what you've learned with the preliminary implementation?

DEMO (Jake, Perez)
Show bits and pieces of a planned working prototype. Briefly demo your progress so far on the classroom computer.

Your progress report will be graded on:
• Progress with your game
• Completeness of your report
• Quality of your writing
• How much it's like that food pyramid game I love

**Comment by jakeharris** [comment]
Thought it was "should be most of the way through layer 0 or perhaps even layer 1"? Though if you are just unaware/forgetting that Pierce zero-indexed them this is not an issue. Just a bit scary haha. We're most of the way through layer 0 with some work done in layer 1 already.

**Comment by smockle** [comment]
@javakat Not sure what you mean. I copied this straight from Canvas. This is something we have to submit Wednesday.

**Comment by smockle** [comment]
@javakat Oh, you're talking about the "You should be most of the way through layer 1 or perhaps even 2" line. That's Dr. Seals, not me. For our purposes it should be Layer 0/1, like you said. I'll update the issue description to make this more clear.

**Comment by jakeharris** [comment]
@smockle Thanks.

**Comment by smockle** [comment]
Superseded by #30. Closing.
