### ISSUE TITLE
Determine whether Unity can apply the graphics filters we need

### ISSUE THREAD

**Issue by smockle** [smockle-archive/foodfight#29]
Card backgrounds need to be blurred, and possibly darkened or colorized. Blocker for #26.

**Comment by jakeharris** [comment]
https://docs.unity3d.com/Documentation/Components/comp-ImageEffects.html

**Comment by jakeharris** [comment]
http://forum.unity3d.com/threads/198568-Epic-Radial-Blur-Effect-for-Unity-Indie may help
