### ISSUE TITLE
Movement required before attack

### ISSUE THREAD

**Issue by pierceboggan** [smockle-archive/foodfight#35]
Description of Behavior:
Double attacks are not allowed. I must first move before I can attack. Not sure if this is part of the design, but I would think that I would be able to utilize my turn to attack. What if I wish to attack and then move? Is this allowed?

Expected:
- Attack, then move
- Attack, then attack

Actual
- Move, then attack

**Comment by robert-p-rez** [comment]
I believe dp has solved this, can we get a confirmation?

**Comment by Alressun** [comment]
Intended. Potential actions are:

Move, then attack
Do not move, attack

**Comment by jakeharris** [comment]
Concurred. Closing this.
